version: 2

before:
  hooks:
    - go mod tidy

builds:
- id: verdex-cli
  binary: verdex

  env:
    - CGO_ENABLED=0

  goos: [windows,linux,darwin]
  goarch: [amd64,386,arm,arm64]
  ignore:
    - goos: darwin
      goarch: 386
    - goos: windows
      goarch: arm
    - goos: windows
      goarch: arm64

  ldflags:
    - -X github.com/verdexlab/verdex/verdex/core.releaseEnvironment=release-binary

archives:
- format: zip
  id: verdex
  builds: [verdex-cli]
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ if eq .Os "darwin" }}macOS{{ else }}{{ .Os }}{{ end }}_{{ .Arch }}'

checksum:
  algorithm: sha256
