info:
  product: keycloak
  author: pierreavn

resolve:
  type: regex
  method: GET
  path: '/resources/{{resourcesId}}/admin/keycloak.v2/assets/{{reactMainName}}-{{reactAdminMainId}}.js'
  part: body
  regex: 'import\("\./DetailSettings-([a-zA-Z0-9-_]+)\.js"\)'
  group: 1
